---
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for creating an s3 bucket and a dynamo db table that the code uses.
Resources:
    ddbtable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
            -
                AttributeName: "ROWID"
                AttributeType: "N"
            KeySchema:
            -
                AttributeName: "ROWID"
                KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: "20"
                WriteCapacityUnits: "20"
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
             AccessControl: BucketOwnerFullControl
Outputs:
  S3Bucket:
    Description: S3 bucket for the workshop
    Value: !Ref Bucket
  DynamoDBTable:
    Description: DynamoDB table created for the workshop
    Value: !Ref ddbtable


